services:
  postgres:
    image: postgres:15
    container_name: lms-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - keycloak_network
  redis:
    image: redis:latest
    container_name: lms_redis
    ports:
      - "6379:6379"
    networks:
      - redis_network
    volumes:
      - redis_data:/data
    restart: always
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: lms_redisinsight
    ports:
      - "5540:5540"
    networks:
      - redis_network
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/${DB_NAME}
      KC_DB_USERNAME: ${DB_USERNAME}
      KC_DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8083:8080
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network
networks:
  redis_network:
    driver: bridge
  keycloak_network:
    driver: bridge
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
